config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'employees#index'

  resources :job_roles, except: %i[index show destroy]
  resources :workspaces, except: %i[index show destroy]
  resources :employees
  resources :users, exepct: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :phone, :email, :cell_phone, presence: true
  validates :phone, :email, :cell_phone, uniqueness: true

  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :registration, :name, presence: true
  validates :registration, :name, uniqueness: true

  enum situation: { 'Solteiro(a)': 0, 'Casado(a)': 1, 'Divorciado(a)': 2, 'Viúvo(a)': 3 }
  enum genre: { Masculino: 0, Feminino: 1 }

  belongs_to :workspace
  belongs_to :job_role
  has_many :contacts, dependent: :destroy
  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true

  scope :search_field, -> (search){
    where("name like :field or registration like :field", field: "%#{search}%") if search.present?
  }

  validates_uniqueness_of :workspace_id, :scope => :job_role_id
end

app/models/job_role.rb
class JobRole < ApplicationRecord
  validates :title, presence: true
  has_many :employees

  scope :ordered_job, -> { order(id: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :ordered_user, -> { order(id: :asc) }
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  validates :title, presence: true
  has_many :employees

  scope :ordered_work, -> { order(id: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employees, only: %i[edit show update destroy]
  def index
    @employees = Employee.search_field(params[:search])
    @workspaces = Workspace.ordered_work
    @job_roles = JobRole.ordered_job
    @users = User.ordered_user
  end

  def show    
  end
  
  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employees_params)
    if @employee.save
      redirect_to employees_path, notice: "#{@employee.name} cadastrada(o) com sucesso!"
    else
      flash.now[:alert] = @employee.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit    
  end

  def update
    if @employee.update(employees_params)
      redirect_to employees_path, notice: "#{@employee.name} atualizada(o) com sucesso!"
    else
      flash.now[:alert] = @employee.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @employee.destroy
      redirect_to employees_path, notice: "#{@employee.name} excluída(o) com sucesso!"
    else
      flash.now[:alert] = @employee.errors.full_messages.to_sentence
      render :index
    end
  end
    
  private

  def set_employees
    @employee = Employee.find(params[:id])
  end

  def employees_params
    params.require(:employee).permit(:registration, :name, :date_birth, :birth_town, :birth_state, :workspace_id, :job_role_id, :situation, :genre, 
                                    contacts_attributes: [:id, :phone, :email, :cell_phone, :_destroy])
  end
end

app/controllers/job_roles_controller.rb
class JobRolesController < ApplicationController
  before_action :set_job_role, only: %i[edit update]

  def new
    @job_role = JobRole.new
  end

  def create
    @job_role = JobRole.new(job_role_params)
    if @job_role.save
      redirect_to employees_path, notice: "#{@job_role.title} cadastrada(o) com sucesso!"
    else
      flash.now[:alert] = @job_role.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @job_role.update(job_role_params)
      redirect_to employees_path, notice: "#{@job_role.title} atualizado com sucesso!"
    else
      flash.now[:alert] = @job_role.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_job_role
    @job_role = JobRole.find(params[:id])
  end

  def job_role_params
    params.require(:job_role).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_users, only: %i[edit update]
  before_action :allow_without_password, only: [:update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to employees_path, notice: "#{@user.name} cadastrado com sucesso!"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(users_params)
      redirect_to employees_path, notice: "#{@user.name} atualizado com sucesso!"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to employees_path, notice: "#{@user.name} excluido com sucesso!"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
    end
  end

  private

  def set_users
    @user = User.find(params[:id])
  end

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

  # remove o input da validação do devise
  def allow_without_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :set_workspaces, only: %i[edit update]
  
  def new
    @workspace = Workspace.new
  end

  def create
    @workspace = Workspace.new(workspaces_params)
    if @workspace.save
      redirect_to employees_path, notice: "#{@workspace.title} cadastrada(o) com sucesso!"
    else
      flash.now[:alert] = @workspace.errors.full_messages.to_sentence
      render "new"
    end
  end

  def edit    
  end

  def update
    if @workspace.update(workspaces_params)
      redirect_to employees_path, notice: "#{@workspace.title} atualizado com sucesso!"
    else
      flash.now[:alert] = @workspace.errors.full_messages.to_sentence
      render "edit"
    end
  end

  private

  def set_workspaces
    @workspace = Workspace.find(params[:id])
  end
  

  def workspaces_params
    params.require(:workspace).permit(:title)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def toastr_flash_class(type)
    case type
    when "alert"
      "toastr.error"
    when "notice"
      "toastr.success"
    else
      "toastr.info"
    end
end
end

app/helpers/employees_helper.rb
module EmployeesHelper

end

app/helpers/job_roles_helper.rb
module JobRolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/employees/_contact_fields.html.erb
<div class="nested-fields">
  <div class="row mt-3">
    <div class="col-md-3">
      <%= f.label :phone %>
      <%= f.text_field :phone, class: "form-control phone" %>
    </div>
    <div class="col-md-3">
      <%= f.label :cell_phone %>
      <%= f.text_field :cell_phone, class: "form-control phone" %>
    </div>
    <div class="col-md-4">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <label for="">Remover</label> <br>
      <%= link_to_remove_association 'remover', f, class: "btn btn-danger" %>
    </div>
  </div>
</div>
<script>
  $(".phone").bind('input propertychange',function(){
  
    var texto = $(this).val();
  
    texto = texto.replace(/[^\d]/g, '');
  
    if (texto.length > 0)
    {
    texto = "(" + texto;
  
        if (texto.length > 3)
        {
            texto = [texto.slice(0, 3), ") ", texto.slice(3)].join('');
        }
        if (texto.length > 12)
        {
            if (texto.length > 13)
                texto = [texto.slice(0, 10), "-", texto.slice(10)].join('');
            else
                texto = [texto.slice(0, 9), "-", texto.slice(9)].join('');
        }
            if (texto.length > 15)
               texto = texto.substr(0,15);
    }
   $(this).val(texto);
  })
</script>

app/views/employees/edit.html.erb
<div class="container">
<h4 class="mt-5">Editando Funcionario!</h4>
<hr>
<%= render 'employees/shared/form' %>
</div>

app/views/employees/index.html.erb
<div class="container">
  <div class="row mt-3 text-center">
    <div class="col-md-3">
      <button type="button" style="width:100%;" class="btn btn-primary" data-toggle="modal" data-target="#workspace">
        Setores
      </button>
    </div>
    <div class="col-md-3">
      <button type="button" style="width:100%;" class="btn btn-primary" data-toggle="modal" data-target="#jobrole">
        Funções
      </button>
    </div>
    <div class="col-md-3">
      <button type="button" style="width:100%;" class="btn btn-primary" data-toggle="modal" data-target="#users">
        Usuarios
      </div>
      <div class="col-md-3">
        <%= link_to 'Cadastrar Funcionario', new_employee_path, style:"width:100%;", class:"btn btn-success" %>
      </div>
    </div>
    <hr>
    <div class="row">
      <%= form_tag(employees_path, method: 'get', class:'form-inline') do %>
        <div class="form-group mb-2">
          <input class="form-control" id="mySearch" type="text" placeholder="Search..">
        </div>
        <h4 class="ml-3">ou</h4>
        <div class="form-group mx-sm-3 mb-2">
          <label for="inputPassword2" class="sr-only">Password</label>
          <input class="form-control" name="search" type="text" placeholder="Search 2..">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Buscar</button>
      <% end %>
      <div class="table-responsive mt-3">
        <h4>Funcionarios Cadastrados</h4>
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">Matricula</th>
              <th scope="col">Nome</th>
              <th scope="col">Data nascimento</th>
              <th scope="col">Sexo</th>
              <th scope="col">Lotação</th>
              <th scope="col">Cargo</th>
              <th scope="col">Ações</th>
            </tr>
          </thead>
          <tbody id="myTable">
            <% @employees.each do |employee| %>
              <tr>
                <th scope="row"><%= employee.registration %></th>
                <td><%= employee.name %></td>
                <td><%= employee.date_birth.strftime("%d/%m/%Y") %></td>
                <td><%= employee.genre %></td>
                <td><%= employee.workspace.title %></td>
                <td><%= employee.job_role.title %></td>
                <td>
                  <%= link_to "<button class='btn btn-secondary btn-sm'><i class='fa fa-pencil'></i></button>".html_safe, edit_employee_path(employee) %>
                  <%= link_to "<button class='btn btn-primary btn-sm'><i class='fa fa-eye'></i></i></button>".html_safe, employee_path(employee) %>
                  <%= link_to "<button class='btn btn-danger btn-sm'><i class='fa fa-times'></i></button>".html_safe, employee_path(employee), method: :delete, data:{ confirm: 'Tem certeza que deseja Excluir?'} %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%= render 'employees/shared/modal_workspaces' %>
  <%= render 'employees/shared/modal_job_roles' %>
  <%= render 'employees/shared/modal_users' %>
  <script>
    $(document).ready(function(){
      $("#mySearch").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
  </script>

app/views/employees/new.html.erb
<div class="container">
<h4 class="mt-5">Cadastrando Funcionario!</h4>
<hr>
<%= render 'employees/shared/form' %>
</div>

app/views/employees/shared/_form.html.erb
<%= form_with model: @employee, local: true do |f| %>
  <div class="row">
    <div class="col-md-2">
      <label>Matricula</label>
      <%= f.text_field :registration, class: "form-control mb-2 text-capitalize", type:"text", placeholder:"12345" %>
    </div>
    <div class="col-md-4">
      <label>Nome</label>
      <%= f.text_field :name, class: "form-control mb-2 text-capitalize", type:"text", placeholder:"Joao Silva" %>
    </div>
    <div class="col-md-3">
      <label>Data de Nascimento</label>
      <%= f.date_field :date_birth, class: "form-control mb-2" %>
    </div>
    <div class="col-md-3">
      <label>Cidade</label>
      <%= f.text_field :birth_town, class: "form-control mb-2 text-capitalize", placeholder:"Goiânia" %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-3">
      <label>Estado</label>
      <%= f.text_field :birth_state, class: "form-control mb-2 text-capitalize", type:"text", placeholder:"Goiás" %>
    </div>
    <div class="col-md-2">
      <label>Função</label>
      <%= collection_select(:employee, :job_role_id, JobRole.all, :id, :title, { prompt: "Selecione" }, { class: "form-control" }) %>
    </div>
    <div class="col-md-3">
      <label>Setor</label>
      <%= collection_select(:employee, :workspace_id, Workspace.all, :id, :title, { prompt: "Selecione" }, { class: "form-control" }) %>
    </div>
    <div class="col-md-2">
      <label>Estado Civil</label>
      <%= f.select(:situation, Employee.situations.keys, { prompt: "Selecione" }, { class: "form-control" }) %>
    </div>
    <div class="col-md-2">
      <label>Sexo</label>
      <%= f.select(:genre, Employee.genres.keys, { prompt: "Selecione" }, { class: "form-control" }) %>
    </div>
  </div>
  <div class="row ml-1 mt-5">
    <h4>Informações de contato!</h4>
  </div>
  <div id="contacts">
    <%= f.fields_for :contacts do |contact| %>
      <%= render 'contact_fields', f: contact %>
    <% end %>
    <%= link_to_add_association 'Adicionar', f, :contacts, class: "btn btn-success mt-2" %>
  </div>
  <hr>
  <div class="row mt-5 ml-1">
      <%= f.submit class: "btn btn-success", data: { disable_with: "Criando....⌛" } %>
      <%= link_to "Cancelar", employees_path, class: "btn btn-danger ml-1" %>
  </div>
<% end %>

app/views/employees/shared/_modal_job_roles.html.erb
<!-- Modal -->
<div class="modal fade" id="jobrole" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Funções Cadastradas</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Código</th>
                <th scope="col">Descrição</th>
                <th scope="col">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @job_roles.each do |job_role| %>
                <tr>
                  <th scope="row"><%= job_role.id %></th>
                  <td><%= job_role.title %></td>
                  <td><%= link_to 'Editar', edit_job_role_path(job_role), class:"btn btn-primary" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <%= link_to 'Adicionar', new_job_role_path, class:"btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/employees/shared/_modal_users.html.erb
<!-- Modal -->
<div class="modal fade" id="users" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Usuarios Cadastrados</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <th scope="row"><%= user.name %></th>
                  <td><%= user.email %></td>
                  <td><%= link_to 'Editar', edit_user_path(user), class:"btn btn-primary" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <%= link_to 'Adicionar', new_user_path, class:"btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/employees/shared/_modal_workspaces.html.erb
<!-- Modal -->
<div class="modal fade" id="workspace" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Setores Cadastrados</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Código</th>
                <th scope="col">Descrição</th>
                <th scope="col">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @workspaces.each do |workspace| %>
                <tr>
                  <th scope="row"><%= workspace.id %></th>
                  <td><%= workspace.title %></td>
                  <td><%= link_to 'Editar', edit_workspace_path(workspace), class:"btn btn-primary" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <%= link_to 'Adicionar', new_workspace_path, class:"btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<div class="container">
  <h4 class="text-center mt-4">Dados Cadastrais Funcionário</h4>
  <hr>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <label>Matricula: </label>
        <input type="text" class="form-control" value="<%= @employee.registration %>" readonly>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Nome: </label>
        <input type="text" class="form-control" value="<%= @employee.name %>" readonly>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label>Data de Nascimento: </label>
        <input type="text" class="form-control" value="<%= @employee.date_birth.strftime("%d/%m/%Y") %>" readonly>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <label>Sexo: </label>
        <input type="text" class="form-control" value="<%= @employee.genre %>" readonly>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label>Lotação: </label>
        <input type="text" class="form-control" value="<%= @employee.workspace.title %>" readonly>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label>Função: </label>
        <input type="text" class="form-control" value="<%= @employee.job_role.title %>" readonly>
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <label>Voltar: </label> <br>
        <%= link_to "<button class='btn btn-info' style='width:100%;'><i class='fa fa-arrow-left'></i></button>".html_safe, employees_path  %>
      </div>
    </div>
  </div>
  <hr>
  <h4 class="text-center mt-4">Contatos Funcionário</h4>
  <% @employee.contacts.each do |contact| %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <label>Telefone: </label>
        <input type="text" class="form-control" value="<%= contact.phone %>" readonly>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label>Celular: </label>
        <input type="text" class="form-control" value="<%= contact.cell_phone %>" readonly>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label>E-mail: </label>
        <input type="text" class="form-control" value="<%= contact.email %>" readonly>
      </div>
    </div>
  </div>
<% end %>
              
</div>

app/views/job_roles/_form.html.erb
<%= form_with model: @job_role, local: true do |f| %>
  <div class="col-md-6">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control mb-2", type:"text", placeholder:"Diretoria"%>
  </div>
  <div class="col-md-3">
    <%= f.submit class: "btn btn-success", data: { disable_with: "Criando....⌛" } %>
    <%= link_to "Cancelar", employees_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/job_roles/edit.html.erb
<div class="container">
  <h4 class="mt-5">Editando Função!</h4>
  <hr>
  <%= render 'form' %>
</div>

app/views/job_roles/new.html.erb
<div class="container">
  <h4 class="mt-5">Cadastrando Função!</h4>
  <hr>
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RhChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to root_path, class:"navbar-brand" do %>
        <%= image_tag 'guiarh-cor.png' %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <span class="nav-link">Bem vindo(a)! <%= current_user.name%></span>
            </li>
            <li class="nav-item">
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Editar Perfil', edit_user_path(current_user), class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>
<%= content_tag(:script) do %>
  <% flash.each do |type, message| %>
    <%= toastr_flash_class("#{type}") %>('<%= message %>')
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f| %>
  <div class="col-md-4">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control mb-2", type:"text", placeholder:"Joao Silva"%>
  </div>
    <div class="col-md-4">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control mb-2", type:"email", placeholder:"teste@test.com"%>
  </div>
      <div class="col-md-4">
    <%= f.label :password %>
    <%= f.text_field :password, class: "form-control mb-2", type:"password"%>
  </div>
        <div class="col-md-4">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation, class: "form-control mb-2", type:"password"%>
  </div>
  <div class="col-md-4">
    <%= f.submit class: "btn btn-success", data: { disable_with: "Criando....⌛" } %>
    <%= link_to "Cancelar", employees_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h4 class="mt-5">Editando Usuario!</h4>
  <hr>
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h4 class="mt-5">Cadastrando Usuario!</h4>
  <hr>
  <%= render 'form' %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/workspaces/_form.html.erb
<%= form_with model: @workspace, local: true do |f| %>
  <div class="col-md-6">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control mb-2", type:"text", placeholder:"Comercial"%>
  </div>
  <div class="col-md-3">
    <%= f.submit class: "btn btn-success", data: { disable_with: "Criando....⌛" } %>
    <%= link_to "Cancelar", employees_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/workspaces/edit.html.erb
<div class="container">
  <h4 class="mt-5">Editando Setor!</h4>
  <hr>
  <%= render 'form' %>
</div>

app/views/workspaces/new.html.erb
<div class="container">
  <h4 class="mt-5">Cadastrando Setor!</h4>
  <hr>
  <%= render 'form' %>
</div>